/**
 * Phase 5.12: Build a minimal Font Awesome CSS (css/icons.css) containing
 * ONLY the icons actually used across the project.
 *
 * - Scans HTML/JS/CSS for icon usage (static classes + quoted literals)
 * - Reads Font Awesome metadata (fa-metadata.json) for unicode codepoints
 * - Emits @font-face rules only for font styles that are needed
 * - Self-hosted fonts live in css/webfonts/
 *
 * Usage: node scripts/build-icons.js
 */
const fs = require('fs');
const path = require('path');

const NL = String.fromCharCode(10);

// ── 1. Collect used icons ───────────────────────────────────────
const usedIcons = new Map(); // name -> Set of prefixes ('solid'|'regular'|'brands')

function addIcon(name, prefix) {
    if (name === 'fa-xxx') return; // template placeholder, not a real icon
    if (!usedIcons.has(name)) usedIcons.set(name, new Set());
    if (prefix) usedIcons.get(name).add(prefix);
}

function walk(dir) {
    for (const f of fs.readdirSync(dir)) {
        const p = path.join(dir, f);
        const st = fs.statSync(p);
        if (st.isDirectory()) {
            if (f === 'node_modules' || f === '.git' || f === '.vercel' || f === 'scripts') continue;
            walk(p);
        } else if (/\.(html|js|css)$/.test(f)) {
            const c = fs.readFileSync(p, 'utf8');
            let m;
            // Static usage: fa-solid fa-xxx / fa-regular fa-xxx / fa-brands fa-xxx
            const re = /fa-(solid|regular|brands)\s+(fa-[a-z0-9-]+)/g;
            while ((m = re.exec(c)) !== null) addIcon(m[2], m[1]);
            // Quoted literals: icon: 'fa-xxx' (dynamic tool.icon / field.icon / insight.icon)
            const litRe = /['"](fa-[a-z0-9-]+)['"]/g;
            while ((m = litRe.exec(c)) !== null) addIcon(m[1], null);
        }
    }
}

walk('.');

// ── 2. Load FA metadata ─────────────────────────────────────────
const metaPath = path.join(__dirname, '..', 'fa-metadata.json');
if (!fs.existsSync(metaPath)) {
    console.error('fa-metadata.json not found. Download it first:');
    console.error('  curl -sL -o fa-metadata.json https://raw.githubusercontent.com/FortAwesome/Font-Awesome/6.5.1/metadata/icons.json');
    process.exit(1);
}
const metadata = JSON.parse(fs.readFileSync(metaPath, 'utf8'));

// ── 3. Resolve style per icon & detect needed fonts ─────────────
const missing = [];
const resolved = []; // { cls, unicode, prefix }

for (const [name, prefixes] of [...usedIcons.entries()].sort()) {
    const shortName = name.replace(/^fa-/, '');
    const info = metadata[shortName];
    if (!info || !info.unicode) {
        missing.push(name);
        continue;
    }
    let prefix;
    if (prefixes.size > 0) {
        // Use the first explicitly-used prefix that the icon supports
        prefix = [...prefixes].find(px => info.styles.includes(px)) || [...prefixes][0];
    } else {
        // No explicit prefix — pick sensibly: brands-only icons -> brands, else solid
        prefix = info.styles.includes('solid') ? 'solid'
               : info.styles.includes('brands') ? 'brands'
               : info.styles[0];
    }
    resolved.push({ cls: name, unicode: info.unicode, prefix });
}

if (missing.length) {
    console.warn('WARNING: icons not found in FA metadata (skipped):');
    missing.forEach(mn => console.warn('  ', mn));
}

const neededFonts = new Set(resolved.map(r => r.prefix));

// ── 4. Generate CSS ─────────────────────────────────────────────
const FONT_FACES = {
    solid: `@font-face {
  font-family: "Font Awesome 6 Free";
  font-style: normal;
  font-weight: 900;
  font-display: block;
  src: url("webfonts/fa-solid-900.woff2") format("woff2");
}`,
    regular: `@font-face {
  font-family: "Font Awesome 6 Free";
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url("webfonts/fa-regular-400.woff2") format("woff2");
}`,
    brands: `@font-face {
  font-family: "Font Awesome 6 Brands";
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url("webfonts/fa-brands-400.woff2") format("woff2");
}`
};

let css = `/*!
 * GetCalcu minimal icon subset — generated by scripts/build-icons.js
 * Based on Font Awesome Free 6.5.1 (CC BY 4.0 / OFL 1.1)
 * Contains only the ${resolved.length} icons used by this site.
 */
`;

for (const f of ['solid', 'regular', 'brands']) {
    if (neededFonts.has(f)) css += FONT_FACES[f] + NL + NL;
}

css += `.fa-solid, .fa-regular, .fa-brands {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  display: var(--fa-display, inline-block);
  font-style: normal;
  font-variant: normal;
  line-height: 1;
  text-rendering: auto;
}
.fa-solid { font-family: "Font Awesome 6 Free"; font-weight: 900; }
.fa-regular { font-family: "Font Awesome 6 Free"; font-weight: 400; }
.fa-brands { font-family: "Font Awesome 6 Brands"; font-weight: 400; }
` + NL;

for (const r of resolved) {
    css += `.${r.prefix}.${r.cls}::before { content: "\\${r.unicode}"; }` + NL;
}

const outPath = path.join(__dirname, '..', 'css', 'icons.css');
fs.writeFileSync(outPath, css);

console.log('Generated css/icons.css with ' + resolved.length + ' icons.');
console.log('Fonts needed: ' + [...neededFonts].join(', '));