/**
 * PDF Module
 * 
 * PDF generation with consistent branding and layouts.
 * Provides PDF export functionality for calculator results.
 * 
 * @module modules/pdf
 */

// ── PDF Generation ─────────────────────────────────────────────

/**
 * Generate PDF from calculator results
 * @param {Object} options - PDF options
 * @param {string} options.title - Document title
 * @param {string} options.content - HTML content
 * @param {string} options.filename - Output filename
 * @param {Object} options.metadata - PDF metadata
 */
export function generatePDF(options = {}) {
    const {
        title = 'Calculator Results',
        content = '',
        filename = 'results.pdf',
        metadata = {}
    } = options;
    
    // Check if we have the required libraries
    if (typeof window.jspdf === 'undefined' && typeof window.jspdf === 'undefined') {
        console.error('PDF generation library not loaded. Please include jsPDF.');
        return null;
    }
    
    try {
        // Dynamic import of jsPDF
        const { jsPDF } = window.jspdf || window.jspdf;
        const doc = new jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: 'a4'
        });
        
        // Add metadata
        if (metadata.author) doc.setProperties({ author: metadata.author });
        if (metadata.title) doc.setProperties({ title: metadata.title });
        if (metadata.subject) doc.setProperties({ subject: metadata.subject });
        
        // Add header
        doc.setFontSize(20);
        doc.setTextColor(99, 102, 241); // Primary color
        doc.text(title, 20, 20);
        
        // Add line
        doc.setDrawColor(99, 102, 241);
        doc.setLineWidth(0.5);
        doc.line(20, 25, 190, 25);
        
        // Add content
        doc.setFontSize(12);
        doc.setTextColor(31, 41, 55);
        
        let yPosition = 35;
        const pageHeight = doc.internal.pageSize.height;
        const margin = 20;
        
        // Parse and add HTML content
        const tempDiv = document.createElement('div');
        tempDiv.innerHTML = content;
        
        const elements = tempDiv.querySelectorAll('h1, h2, h3, p, table, .result-box');
        
        elements.forEach(element => {
            // Check if we need a new page
            if (yPosition > pageHeight - margin) {
                doc.addPage();
                yPosition = margin;
            }
            
            const tagName = element.tagName.toLowerCase();
            
            if (tagName === 'h1') {
                doc.setFontSize(18);
                doc.setFont(undefined, 'bold');
                doc.text(element.textContent, margin, yPosition);
                yPosition += 8;
            } else if (tagName === 'h2') {
                doc.setFontSize(14);
                doc.setFont(undefined, 'bold');
                doc.text(element.textContent, margin, yPosition);
                yPosition += 6;
            } else if (tagName === 'h3') {
                doc.setFontSize(12);
                doc.setFont(undefined, 'bold');
                doc.text(element.textContent, margin, yPosition);
                yPosition += 5;
            } else if (tagName === 'p') {
                doc.setFontSize(10);
                doc.setFont(undefined, 'normal');
                const lines = doc.splitTextToSize(element.textContent, 170);
                doc.text(lines, margin, yPosition);
                yPosition += lines.length * 5;
            } else if (tagName === 'table') {
                yPosition = addTableToPDF(doc, element, yPosition, margin);
            } else if (element.classList.contains('result-box')) {
                doc.setDrawColor(229, 231, 235);
                doc.setFillColor(249, 250, 251);
                doc.rect(margin, yPosition, 170, 30, 'FD');
                
                doc.setFontSize(10);
                doc.setFont(undefined, 'normal');
                const lines = doc.splitTextToSize(element.textContent, 165);
                doc.text(lines, margin + 3, yPosition + 5);
                yPosition += Math.max(30, lines.length * 5 + 10);
            }
            
            yPosition += 3;
        });
        
        // Add footer
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(9);
            doc.setTextColor(156, 163, 175);
            doc.text(
                `Generated by GetCalcu - ${new Date().toLocaleDateString()} - Page ${i} of ${pageCount}`,
                margin,
                doc.internal.pageSize.height - 10
            );
        }
        
        // Save the PDF
        doc.save(filename);
        
        return {
            success: true,
            filename,
            pages: pageCount
        };
    } catch (error) {
        console.error('PDF generation failed:', error);
        return {
            success: false,
            error: error.message
        };
    }
}

/**
 * Add table to PDF
 * @param {Object} doc - jsPDF instance
 * @param {HTMLElement} tableElement - Table element
 * @param {number} yPosition - Current Y position
 * @param {number} margin - Page margin
 * @returns {number} New Y position
 */
function addTableToPDF(doc, tableElement, yPosition, margin) {
    const rows = tableElement.querySelectorAll('tr');
    const pageHeight = doc.internal.pageSize.height;
    const rowHeight = 8;
    
    rows.forEach((row, rowIndex) => {
        // Check if we need a new page
        if (yPosition > pageHeight - margin - rowHeight) {
            doc.addPage();
            yPosition = margin;
        }
        
        const cells = row.querySelectorAll('th, td');
        let xPosition = margin;
        
        cells.forEach((cell, cellIndex) => {
            const cellText = cell.textContent.trim();
            const cellWidth = 170 / cells.length;
            
            // Draw cell border
            doc.setDrawColor(229, 231, 235);
            doc.setLineWidth(0.2);
            doc.rect(xPosition, yPosition, cellWidth, rowHeight);
            
            // Add cell text
            doc.setFontSize(9);
            doc.setFont(undefined, rowIndex === 0 ? 'bold' : 'normal');
            doc.setTextColor(rowIndex === 0 ? 75, 85, 99 : 31, 41, 55);
            
            const lines = doc.splitTextToSize(cellText, cellWidth - 2);
            doc.text(lines, xPosition + 1, yPosition + 5);
            
            xPosition += cellWidth;
        });
        
        yPosition += rowHeight;
    });
    
    return yPosition + 5;
}

/**
 * Generate PDF from calculator result
 * @param {Object} tool - Tool definition
 * @param {Object} result - Calculation result
 * @param {Object} options - PDF options
 * @returns {Object} PDF generation result
 */
export function generateResultsPDF(tool, result, options = {}) {
    const {
        filename = `${tool.id}-results.pdf`,
        includeCharts = true,
        includeTable = true
    } = options;
    
    // Build HTML content
    let html = '';
    
    // Title
    html += `<h1>${escapeHtml(tool.name)} - Results</h1>`;
    
    // Stats
    if (result.stats && result.stats.length > 0) {
        html += '<h2>Summary</h2>';
        html += '<div class="result-box">';
        
        result.stats.forEach(stat => {
            html += `
                <div style="display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #E5E7EB;">
                    <span style="font-weight: 600; color: #6B7280;">${escapeHtml(stat.label)}</span>
                    <span style="font-weight: 700; color: #1F2937; ${stat.highlight ? 'font-size: 16px; color: #6366F1;' : ''}">${escapeHtml(stat.value)}</span>
                </div>
            `;
        });
        
        html += '</div>';
    }
    
    // Insight
    if (result.insight) {
        html += `
            <div class="result-box" style="border-left: 4px solid #6366F1; background: #F9FAFB;">
                <h3 style="font-size: 14px; margin-bottom: 8px; color: #6366F1;">${escapeHtml(result.insight.headline)}</h3>
                <p style="color: #6B7280; font-size: 12px;">${escapeHtml(result.insight.detail)}</p>
            </div>
        `;
    }
    
    // Table
    if (includeTable && result.table) {
        html += '<h2>Details</h2>';
        html += '<table><thead><tr>';
        
        result.table.columns.forEach(col => {
            html += `<th style="background: #F9FAFB; padding: 8px; text-align: left; border-bottom: 1px solid #E5E7EB; font-weight: 600;">${escapeHtml(col.label)}</th>`;
        });
        
        html += '</tr></thead><tbody>';
        
        result.table.rows.forEach(row => {
            html += '<tr>';
            result.table.columns.forEach(col => {
                html += `<td style="padding: 8px; border-bottom: 1px solid #E5E7EB;">${escapeHtml(String(row[col.key] || '-'))}</td>`;
            });
            html += '</tr>';
        });
        
        html += '</tbody></table>';
    }
    
    // Generate PDF
    return generatePDF({
        title: tool.name,
        content: html,
        filename,
        metadata: {
            author: 'GetCalcu',
            title: tool.name + ' - Results',
            subject: 'Calculator Results'
        }
    });
}

// ── PDF Utilities ──────────────────────────────────────────────

/**
 * Check if PDF generation is supported
 * @returns {boolean} True if supported
 */
export function isPDFSupported() {
    return typeof window.jspdf !== 'undefined' || typeof window.jspdf !== 'undefined';
}

/**
 * Load PDF library dynamically
 * @returns {Promise<void>}
 */
export async function loadPDFLibrary() {
    if (isPDFSupported()) {
        return;
    }
    
    return new Promise((resolve, reject) => {
        const script = document.createElement('script');
        script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
        script.onload = () => resolve();
        script.onerror = () => reject(new Error('Failed to load PDF library'));
        document.head.appendChild(script);
    });
}

/**
 * Create PDF button
 * @param {Object} options - Button options
 * @returns {string} HTML string
 */
export function buildPDFButton(options = {}) {
    const {
        text = 'Download PDF',
        className = 'pdf-btn',
        icon = 'fa-file-pdf'
    } = options;
    
    return `
        <button class="${className}" onclick="window.pdfModules.generate()">
            <i class="fa-solid ${icon}"></i> ${escapeHtml(text)}
        </button>
    `;
}

// ── Global API ─────────────────────────────────────────────────

/**
 * Initialize PDF module globally
 */
export function initPDFGlobal() {
    if (typeof window !== 'undefined') {
        window.pdfModules = {
            generate: (options) => generatePDF(options),
            generatePDF,
            generateResultsPDF,
            loadPDFLibrary,
            isPDFSupported
        };
    }
}

// Auto-initialize
if (typeof window !== 'undefined') {
    initPDFGlobal();
}

// Log module initialization
console.log('PDF module loaded');

// ── Helper Functions ───────────────────────────────────────────

/**
 * Escape HTML to prevent XSS
 * @param {string} str - String to escape
 * @returns {string} Escaped string
 */
function escapeHtml(str) {
    if (str === null || str === undefined) {
        return '';
    }
    
    const div = document.createElement('div');
    div.appendChild(document.createTextNode(String(str)));
    return div.innerHTML;
}