/**
 * Print Module
 * 
 * Print-friendly formatting and print handlers.
 * Provides consistent print functionality across all calculators.
 * 
 * @module modules/print
 */

// ── Print Management ───────────────────────────────────────────

/**
 * Print calculator results
 * @param {Object} options - Print options
 * @param {string} options.title - Print title
 * @param {string} options.content - Content to print
 * @param {boolean} options.openWindow - Open print window (default: true)
 */
export function printResults(options = {}) {
    const {
        title = 'Calculator Results',
        content = '',
        openWindow = true
    } = options;
    
    if (openWindow) {
        const printWindow = window.open('', '_blank', 'width=800,height=600');
        
        if (!printWindow) {
            console.error('Unable to open print window. Please check popup blocker.');
            return;
        }
        
        printWindow.document.write(`
            <!DOCTYPE html>
            <html>
            <head>
                <title>${escapeHtml(title)}</title>
                <style>
                    * { margin: 0; padding: 0; box-sizing: border-box; }
                    body {
                        font-family: 'Inter', 'Segoe UI', Arial, sans-serif;
                        line-height: 1.6;
                        color: #1F2937;
                        max-width: 800px;
                        margin: 0 auto;
                        padding: 40px 20px;
                    }
                    h1 { font-size: 24px; margin-bottom: 20px; border-bottom: 2px solid #6366F1; padding-bottom: 10px; }
                    h2 { font-size: 18px; margin-top: 30px; margin-bottom: 15px; color: #4B5563; }
                    .result-box { background: #F9FAFB; border: 1px solid #E5E7EB; border-radius: 8px; padding: 20px; margin-bottom: 20px; }
                    .result-stat { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #E5E7EB; }
                    .result-stat:last-child { border-bottom: none; }
                    .result-label { font-weight: 600; color: #6B7280; }
                    .result-value { font-weight: 700; color: #1F2937; }
                    .highlight { color: #6366F1; font-size: 18px; }
                    table { width: 100%; border-collapse: collapse; margin-top: 15px; }
                    th, td { padding: 10px; text-align: left; border-bottom: 1px solid #E5E7EB; }
                    th { background: #F9FAFB; font-weight: 600; }
                    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #E5E7EB; font-size: 12px; color: #9CA3AF; text-align: center; }
                    @media print {
                        body { padding: 0; }
                        .no-print { display: none; }
                    }
                </style>
            </head>
            <body>
                ${content}
                <div class="footer">
                    Generated by GetCalcu - ${new Date().toLocaleDateString()}
                </div>
                <script>
                    window.onload = function() {
                        window.print();
                        setTimeout(() => window.close(), 100);
                    };
                </script>
            </body>
            </html>
        `);
        
        printWindow.document.close();
    } else {
        // Print current page
        window.print();
    }
}

/**
 * Create print-friendly content from calculator result
 * @param {Object} tool - Tool definition
 * @param {Object} result - Calculation result
 * @returns {string} Print-ready HTML
 */
export function createPrintContent(tool, result) {
    let html = `<h1>${escapeHtml(tool.name)} - Results</h1>`;
    
    // Add stats
    if (result.stats && result.stats.length > 0) {
        html += '<h2>Summary</h2><div class="result-box">';
        
        result.stats.forEach(stat => {
            const highlightClass = stat.highlight ? 'highlight' : '';
            html += `
                <div class="result-stat">
                    <span class="result-label">${escapeHtml(stat.label)}</span>
                    <span class="result-value ${highlightClass}">${escapeHtml(stat.value)}</span>
                </div>
            `;
        });
        
        html += '</div>';
    }
    
    // Add insight
    if (result.insight) {
        html += `
            <div class="result-box" style="border-left: 4px solid #6366F1;">
                <h3 style="font-size: 16px; margin-bottom: 10px; color: #6366F1;">${escapeHtml(result.insight.headline)}</h3>
                <p style="color: #6B7280;">${escapeHtml(result.insight.detail)}</p>
            </div>
        `;
    }
    
    // Add table
    if (result.table) {
        html += '<h2>Details</h2><div class="result-box">';
        html += '<table><thead><tr>';
        
        result.table.columns.forEach(col => {
            html += `<th>${escapeHtml(col.label)}</th>`;
        });
        
        html += '</tr></thead><tbody>';
        
        result.table.rows.forEach(row => {
            html += '<tr>';
            result.table.columns.forEach(col => {
                html += `<td>${escapeHtml(String(row[col.key] || '-'))}</td>`;
            });
            html += '</tr>';
        });
        
        html += '</tbody></table></div>';
    }
    
    return html;
}

// ── Print Styles ───────────────────────────────────────────────

/**
 * Inject print styles into page
 * @param {Object} styles - Custom styles
 */
export function injectPrintStyles(styles = {}) {
    const defaultStyles = {
        hideElements: '.no-print, .share-buttons, .related-tools-section, .recommendations-section',
        fontSize: '16px',
        lineHeight: '1.6',
        color: '#1F2937'
    };
    
    const mergedStyles = { ...defaultStyles, ...styles };
    
    const styleId = 'print-styles';
    let styleElement = document.getElementById(styleId);
    
    if (!styleElement) {
        styleElement = document.createElement('style');
        styleElement.id = styleId;
        document.head.appendChild(styleElement);
    }
    
    styleElement.textContent = `
        @media print {
            ${mergedStyles.hideElements} { display: none !important; }
            
            body {
                font-size: ${mergedStyles.fontSize};
                line-height: ${mergedStyles.lineHeight};
                color: ${mergedStyles.color};
            }
            
            .calculator-wrapper {
                box-shadow: none !important;
                border: none !important;
            }
            
            .chart-container {
                page-break-inside: avoid;
            }
            
            table {
                page-break-inside: avoid;
            }
            
            .result-stat-box {
                page-break-inside: avoid;
            }
        }
    `;
}

/**
 * Remove print styles
 */
export function removePrintStyles() {
    const styleElement = document.getElementById('print-styles');
    if (styleElement) {
        styleElement.remove();
    }
}

// ── Print Utilities ────────────────────────────────────────────

/**
 * Check if print dialog is supported
 * @returns {boolean} True if supported
 */
export function isPrintSupported() {
    return typeof window.print === 'function';
}

/**
 * Prepare page for printing
 * @param {Object} options - Options
 */
export function prepareForPrint(options = {}) {
    const {
        hideButtons = true,
        hideNavigation = true,
        hideAds = true
    } = options;
    
    const classesToHide = [];
    
    if (hideButtons) classesToHide.push('.btn-primary, .btn-secondary, .share-buttons');
    if (hideNavigation) classesToHide.push('nav, .navigation, .breadcrumb');
    if (hideAds) classesToHide.push('.ad, .advertisement, [data-ad]');
    
    // Add temporary class to body
    document.body.classList.add('printing');
    
    // Inject styles
    injectPrintStyles({
        hideElements: classesToHide.join(', ')
    });
}

/**
 * Cleanup after printing
 */
export function cleanupAfterPrint() {
    document.body.classList.remove('printing');
    removePrintStyles();
}

// ── Print Event Handlers ───────────────────────────────────────

/**
 * Setup print event listeners
 * @param {Function} beforePrint - Callback before print
 * @param {Function} afterPrint - Callback after print
 */
export function setupPrintEvents(beforePrint, afterPrint) {
    // Modern browsers
    if (window.matchMedia) {
        const mediaQuery = window.matchMedia('print');
        
        mediaQuery.addEventListener('change', (e) => {
            if (e.matches) {
                // Before print
                if (beforePrint) beforePrint();
            } else {
                // After print
                if (afterPrint) afterPrint();
            }
        });
    }
    
    // Fallback for older browsers
    window.addEventListener('beforeprint', () => {
        if (beforePrint) beforePrint();
    });
    
    window.addEventListener('afterprint', () => {
        if (afterPrint) afterPrint();
    });
}

// ── Print Button Builder ───────────────────────────────────────

/**
 * Build print button HTML
 * @param {Object} options - Button options
 * @returns {string} HTML string
 */
export function buildPrintButton(options = {}) {
    const {
        text = 'Print Results',
        className = 'print-btn',
        icon = 'fa-print'
    } = options;
    
    return `
        <button class="${className}" onclick="window.printModules.print()">
            <i class="fa-solid ${icon}"></i> ${escapeHtml(text)}
        </button>
    `;
}

// ── Global API ─────────────────────────────────────────────────

/**
 * Initialize print module globally
 */
export function initPrintGlobal() {
    if (typeof window !== 'undefined') {
        window.printModules = {
            print: () => printResults(),
            printResults,
            createPrintContent,
            prepareForPrint,
            cleanupAfterPrint,
            injectPrintStyles,
            removePrintStyles,
            isPrintSupported
        };
    }
}

// Auto-initialize
if (typeof window !== 'undefined') {
    initPrintGlobal();
}

// Log module initialization
console.log('Print module loaded');

// ── Helper Functions ───────────────────────────────────────────

/**
 * Escape HTML to prevent XSS
 * @param {string} str - String to escape
 * @returns {string} Escaped string
 */
function escapeHtml(str) {
    if (str === null || str === undefined) {
        return '';
    }
    
    const div = document.createElement('div');
    div.appendChild(document.createTextNode(String(str)));
    return div.innerHTML;
}